### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by jvromans** [johnroper100/Blended#1]
It seems that Blended processes content items in the content directory, but not in subdirectories.

**Comment by johnroper100** [comment]
Try updating. pip install -U blended


I pushed an update for this two days ago

**Comment by jvromans** [comment]
I'm on 4.0 now, and still items in subdirectories or content are not picked up.

**Comment by johnroper100** [comment]
Can you post a picture of your directory setup?

**Comment by jvromans** [comment]
Omitting the assets folders in template and build.

- build/bedankt.html
- build/coloured_notes.html
- build/contact_err.html
- build/contact.html
- build/index.html
- config.py
- config.pyc
- content/bedankt.html
- content/coloured_notes.html
- content/contact_err.html
- content/contact.html
- content/foo/bedankt.html
- content/index.html
- templates/content_page.html
- templates/footer.html
- templates/.gitignore
- templates/header.html
- templates/LICENSE
- templates/nav1.html
- templates/nav2.html

**Comment by johnroper100** [comment]
Blended does not currently make the same folder structure in the build folder. All the files from all directories in content are placed in the root of build. Because you have files named the same in the content folder and it's subdirectories, the second file found is overwriting the first. Just rename the files and you should be fine.

**Comment by jvromans** [comment]
This is a real showstopper. My sites usually have many subdirectories (and subsub...) each having at least an index.html.
Also, links from one subdir page to another won't work anymore.

**Comment by johnroper100** [comment]
I am working right now to fix this problem.

**Comment by jvromans** [comment]
I really appreciate your efforts and support, but unless you really like doing what you are doing: There are several 'blended'-like static site builders around that are more complete, more powerful and more mature.

**Comment by johnroper100** [comment]
I fixed that problem. I still need to publish but I will tell you when I
have. Do you have examples of other generators like blended?

**Comment by johnroper100** [comment]
Blended was written to work with my personal workflow

**Comment by johnroper100** [comment]
Ok, that fix is pushed!

**Comment by jvromans** [comment]
Unfortunately, 4.1 yields errors:

Building your Blended files into a website!
Traceback (most recent call last):
  File "/bin/blended", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in
__call__ return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in
invoke return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/blended/__main__.py", line 547, in
build build_files()
  File "/usr/lib/python2.7/site-packages/blended/__main__.py", line 469, in
build_files file_modified =
str(time.ctime(os.path.getmtime(subfolder_folder))) File
"/usr/lib64/python2.7/genericpath.py", line 62, in getmtime return
os.stat(filename).st_mtime OSError: [Errno 2] No such file or directory:
'/home/jv/src/tt2site/Sites/JohanVromans/blended/build/foo/coloured_notes.html'


Note that there is no source content/foo/coloured_notes.html, so I wonder
why it wants to put it in build.

**Comment by jvromans** [comment]
On Fri, 10 Feb 2017 11:43:09 -0800, John Roper <notifications@github.com>
wrote:

> Blended was written to work with my personal workflow

and:

> Do you have examples of other generators like blended?

Several years ago (2004) I wrote the Template Toolkit Site Builder which
has been in production since 2005. It is based on a templating site builder
as described in "Perl Template Toolkit" (O'Reilly, 2004). 

The current version shows its age but this is mostly due to outdated styles,
see e.g. http://johan.vromans.org/extra/tt2site/site/index.html . It is
however very alive and kicking. See e.g. http://www.hetgeluidvanseptember.nl
for a more modern look.

Fun fact: it took me just over an hour to configure it to be 'blended'
lookalike. See e.g. http://www.johanvromans.nl . Note: these are
configuration (templates, styles) changes, not software!

Major differences between blended and tt2site, as far as I can judge from
playing a couple of hours:

- blended handles many input formats, soft sensing. tt2site handles only
  html input (although my current development version handles markdown as
  well)

- tt2site is recursive, but I guess blended will tackle that issue as well.

- tt2site generated sites are position independent. You can build a site
  and then put it in a subdirectory of an existing site -- it will work.

- tt2site uses a powerful templater, the Template Toolkit. See e.g.
  http://tt2.org/docs/manual/Intro.html .

I think the lack of a fullblown templater will prove to be the weakest
point.

But we are all doing it for fun, aren't we?

Regards,
	Johan
