### ISSUE TITLE
Python 3 PIP error: "importlib.util module does not exist"

### ISSUE THREAD

**Issue by Sailsman63** [johnroper100/Blended#3]
When doing `pip install blended` to do a local build of https://github.com/ArtOfIllusion/AOI-website I got the above error.  (thanks for the contribution, BTW!)

I was able to replicate the error by running `pip install importlib.` I'm on arch, so my default python package is python 3. I've done some poking around, and found that the `importlib` module seems to be intended for use with python 2.x only?

I was able to install a secondary package for python 2.7, and was able to successfully install and run blended with that. However, since the blended website states that blended is for use with both python 2 & 3, I thought I'd drop a line here, just in case I'm missing something.

**Comment by johnroper100** [comment]
I use Python 3 to develop and Python 2 to test so this is wierd. Try
installing the previous version.

**Comment by Sailsman63** [comment]
Blended 3.3 does install cleanly in my python 3 environment, and runs correctly as well.

Exact python tool versions as of this moment, all arch packages up to date.:

- python 3.6.0
- pip 9.0.1
